/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.neo.fs.v2.netmap.Clause', null, global);
goog.exportSymbol('proto.neo.fs.v2.netmap.Filter', null, global);
goog.exportSymbol('proto.neo.fs.v2.netmap.NetworkInfo', null, global);
goog.exportSymbol('proto.neo.fs.v2.netmap.NodeInfo', null, global);
goog.exportSymbol('proto.neo.fs.v2.netmap.NodeInfo.Attribute', null, global);
goog.exportSymbol('proto.neo.fs.v2.netmap.NodeInfo.State', null, global);
goog.exportSymbol('proto.neo.fs.v2.netmap.Operation', null, global);
goog.exportSymbol('proto.neo.fs.v2.netmap.PlacementPolicy', null, global);
goog.exportSymbol('proto.neo.fs.v2.netmap.Replica', null, global);
goog.exportSymbol('proto.neo.fs.v2.netmap.Selector', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.neo.fs.v2.netmap.Filter = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.neo.fs.v2.netmap.Filter.repeatedFields_, null);
};
goog.inherits(proto.neo.fs.v2.netmap.Filter, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.neo.fs.v2.netmap.Filter.displayName = 'proto.neo.fs.v2.netmap.Filter';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.neo.fs.v2.netmap.Filter.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.neo.fs.v2.netmap.Filter.prototype.toObject = function(opt_includeInstance) {
  return proto.neo.fs.v2.netmap.Filter.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.neo.fs.v2.netmap.Filter} msg The msg instance to transform.
 * @return {!Object}
 */
proto.neo.fs.v2.netmap.Filter.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: msg.getName(),
    key: msg.getKey(),
    op: msg.getOp(),
    value: msg.getValue(),
    filtersList: jspb.Message.toObjectList(msg.getFiltersList(),
    proto.neo.fs.v2.netmap.Filter.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.neo.fs.v2.netmap.Filter}
 */
proto.neo.fs.v2.netmap.Filter.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.neo.fs.v2.netmap.Filter;
  return proto.neo.fs.v2.netmap.Filter.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.neo.fs.v2.netmap.Filter} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.neo.fs.v2.netmap.Filter}
 */
proto.neo.fs.v2.netmap.Filter.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    case 3:
      var value = /** @type {!proto.neo.fs.v2.netmap.Operation} */ (reader.readEnum());
      msg.setOp(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setValue(value);
      break;
    case 5:
      var value = new proto.neo.fs.v2.netmap.Filter;
      reader.readMessage(value,proto.neo.fs.v2.netmap.Filter.deserializeBinaryFromReader);
      msg.getFiltersList().push(value);
      msg.setFiltersList(msg.getFiltersList());
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.neo.fs.v2.netmap.Filter} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.neo.fs.v2.netmap.Filter.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.neo.fs.v2.netmap.Filter.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.neo.fs.v2.netmap.Filter.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getKey();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getOp();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = this.getValue();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = this.getFiltersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.neo.fs.v2.netmap.Filter.serializeBinaryToWriter
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.neo.fs.v2.netmap.Filter} The clone.
 */
proto.neo.fs.v2.netmap.Filter.prototype.cloneMessage = function() {
  return /** @type {!proto.neo.fs.v2.netmap.Filter} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.neo.fs.v2.netmap.Filter.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.neo.fs.v2.netmap.Filter.prototype.setName = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string key = 2;
 * @return {string}
 */
proto.neo.fs.v2.netmap.Filter.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.neo.fs.v2.netmap.Filter.prototype.setKey = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional Operation op = 3;
 * @return {!proto.neo.fs.v2.netmap.Operation}
 */
proto.neo.fs.v2.netmap.Filter.prototype.getOp = function() {
  return /** @type {!proto.neo.fs.v2.netmap.Operation} */ (jspb.Message.getFieldProto3(this, 3, 0));
};


/** @param {!proto.neo.fs.v2.netmap.Operation} value  */
proto.neo.fs.v2.netmap.Filter.prototype.setOp = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string value = 4;
 * @return {string}
 */
proto.neo.fs.v2.netmap.Filter.prototype.getValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 4, ""));
};


/** @param {string} value  */
proto.neo.fs.v2.netmap.Filter.prototype.setValue = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * repeated Filter filters = 5;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.neo.fs.v2.netmap.Filter>}
 */
proto.neo.fs.v2.netmap.Filter.prototype.getFiltersList = function() {
  return /** @type{!Array.<!proto.neo.fs.v2.netmap.Filter>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.neo.fs.v2.netmap.Filter, 5));
};


/** @param {Array.<!proto.neo.fs.v2.netmap.Filter>} value  */
proto.neo.fs.v2.netmap.Filter.prototype.setFiltersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 5, value);
};


proto.neo.fs.v2.netmap.Filter.prototype.clearFiltersList = function() {
  this.setFiltersList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.neo.fs.v2.netmap.Selector = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.neo.fs.v2.netmap.Selector, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.neo.fs.v2.netmap.Selector.displayName = 'proto.neo.fs.v2.netmap.Selector';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.neo.fs.v2.netmap.Selector.prototype.toObject = function(opt_includeInstance) {
  return proto.neo.fs.v2.netmap.Selector.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.neo.fs.v2.netmap.Selector} msg The msg instance to transform.
 * @return {!Object}
 */
proto.neo.fs.v2.netmap.Selector.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: msg.getName(),
    count: msg.getCount(),
    clause: msg.getClause(),
    attribute: msg.getAttribute(),
    filter: msg.getFilter()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.neo.fs.v2.netmap.Selector}
 */
proto.neo.fs.v2.netmap.Selector.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.neo.fs.v2.netmap.Selector;
  return proto.neo.fs.v2.netmap.Selector.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.neo.fs.v2.netmap.Selector} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.neo.fs.v2.netmap.Selector}
 */
proto.neo.fs.v2.netmap.Selector.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCount(value);
      break;
    case 3:
      var value = /** @type {!proto.neo.fs.v2.netmap.Clause} */ (reader.readEnum());
      msg.setClause(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setAttribute(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setFilter(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.neo.fs.v2.netmap.Selector} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.neo.fs.v2.netmap.Selector.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.neo.fs.v2.netmap.Selector.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.neo.fs.v2.netmap.Selector.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getCount();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = this.getClause();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = this.getAttribute();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = this.getFilter();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.neo.fs.v2.netmap.Selector} The clone.
 */
proto.neo.fs.v2.netmap.Selector.prototype.cloneMessage = function() {
  return /** @type {!proto.neo.fs.v2.netmap.Selector} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.neo.fs.v2.netmap.Selector.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.neo.fs.v2.netmap.Selector.prototype.setName = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional uint32 count = 2;
 * @return {number}
 */
proto.neo.fs.v2.netmap.Selector.prototype.getCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 2, 0));
};


/** @param {number} value  */
proto.neo.fs.v2.netmap.Selector.prototype.setCount = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional Clause clause = 3;
 * @return {!proto.neo.fs.v2.netmap.Clause}
 */
proto.neo.fs.v2.netmap.Selector.prototype.getClause = function() {
  return /** @type {!proto.neo.fs.v2.netmap.Clause} */ (jspb.Message.getFieldProto3(this, 3, 0));
};


/** @param {!proto.neo.fs.v2.netmap.Clause} value  */
proto.neo.fs.v2.netmap.Selector.prototype.setClause = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string attribute = 4;
 * @return {string}
 */
proto.neo.fs.v2.netmap.Selector.prototype.getAttribute = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 4, ""));
};


/** @param {string} value  */
proto.neo.fs.v2.netmap.Selector.prototype.setAttribute = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string filter = 5;
 * @return {string}
 */
proto.neo.fs.v2.netmap.Selector.prototype.getFilter = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 5, ""));
};


/** @param {string} value  */
proto.neo.fs.v2.netmap.Selector.prototype.setFilter = function(value) {
  jspb.Message.setField(this, 5, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.neo.fs.v2.netmap.Replica = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.neo.fs.v2.netmap.Replica, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.neo.fs.v2.netmap.Replica.displayName = 'proto.neo.fs.v2.netmap.Replica';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.neo.fs.v2.netmap.Replica.prototype.toObject = function(opt_includeInstance) {
  return proto.neo.fs.v2.netmap.Replica.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.neo.fs.v2.netmap.Replica} msg The msg instance to transform.
 * @return {!Object}
 */
proto.neo.fs.v2.netmap.Replica.toObject = function(includeInstance, msg) {
  var f, obj = {
    count: msg.getCount(),
    selector: msg.getSelector()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.neo.fs.v2.netmap.Replica}
 */
proto.neo.fs.v2.netmap.Replica.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.neo.fs.v2.netmap.Replica;
  return proto.neo.fs.v2.netmap.Replica.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.neo.fs.v2.netmap.Replica} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.neo.fs.v2.netmap.Replica}
 */
proto.neo.fs.v2.netmap.Replica.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCount(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSelector(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.neo.fs.v2.netmap.Replica} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.neo.fs.v2.netmap.Replica.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.neo.fs.v2.netmap.Replica.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.neo.fs.v2.netmap.Replica.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getCount();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = this.getSelector();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.neo.fs.v2.netmap.Replica} The clone.
 */
proto.neo.fs.v2.netmap.Replica.prototype.cloneMessage = function() {
  return /** @type {!proto.neo.fs.v2.netmap.Replica} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional uint32 count = 1;
 * @return {number}
 */
proto.neo.fs.v2.netmap.Replica.prototype.getCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {number} value  */
proto.neo.fs.v2.netmap.Replica.prototype.setCount = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string selector = 2;
 * @return {string}
 */
proto.neo.fs.v2.netmap.Replica.prototype.getSelector = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.neo.fs.v2.netmap.Replica.prototype.setSelector = function(value) {
  jspb.Message.setField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.neo.fs.v2.netmap.PlacementPolicy = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.neo.fs.v2.netmap.PlacementPolicy.repeatedFields_, null);
};
goog.inherits(proto.neo.fs.v2.netmap.PlacementPolicy, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.neo.fs.v2.netmap.PlacementPolicy.displayName = 'proto.neo.fs.v2.netmap.PlacementPolicy';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.neo.fs.v2.netmap.PlacementPolicy.repeatedFields_ = [1,3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.neo.fs.v2.netmap.PlacementPolicy.prototype.toObject = function(opt_includeInstance) {
  return proto.neo.fs.v2.netmap.PlacementPolicy.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.neo.fs.v2.netmap.PlacementPolicy} msg The msg instance to transform.
 * @return {!Object}
 */
proto.neo.fs.v2.netmap.PlacementPolicy.toObject = function(includeInstance, msg) {
  var f, obj = {
    replicasList: jspb.Message.toObjectList(msg.getReplicasList(),
    proto.neo.fs.v2.netmap.Replica.toObject, includeInstance),
    containerBackupFactor: msg.getContainerBackupFactor(),
    selectorsList: jspb.Message.toObjectList(msg.getSelectorsList(),
    proto.neo.fs.v2.netmap.Selector.toObject, includeInstance),
    filtersList: jspb.Message.toObjectList(msg.getFiltersList(),
    proto.neo.fs.v2.netmap.Filter.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.neo.fs.v2.netmap.PlacementPolicy}
 */
proto.neo.fs.v2.netmap.PlacementPolicy.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.neo.fs.v2.netmap.PlacementPolicy;
  return proto.neo.fs.v2.netmap.PlacementPolicy.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.neo.fs.v2.netmap.PlacementPolicy} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.neo.fs.v2.netmap.PlacementPolicy}
 */
proto.neo.fs.v2.netmap.PlacementPolicy.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.neo.fs.v2.netmap.Replica;
      reader.readMessage(value,proto.neo.fs.v2.netmap.Replica.deserializeBinaryFromReader);
      msg.getReplicasList().push(value);
      msg.setReplicasList(msg.getReplicasList());
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setContainerBackupFactor(value);
      break;
    case 3:
      var value = new proto.neo.fs.v2.netmap.Selector;
      reader.readMessage(value,proto.neo.fs.v2.netmap.Selector.deserializeBinaryFromReader);
      msg.getSelectorsList().push(value);
      msg.setSelectorsList(msg.getSelectorsList());
      break;
    case 4:
      var value = new proto.neo.fs.v2.netmap.Filter;
      reader.readMessage(value,proto.neo.fs.v2.netmap.Filter.deserializeBinaryFromReader);
      msg.getFiltersList().push(value);
      msg.setFiltersList(msg.getFiltersList());
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.neo.fs.v2.netmap.PlacementPolicy} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.neo.fs.v2.netmap.PlacementPolicy.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.neo.fs.v2.netmap.PlacementPolicy.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.neo.fs.v2.netmap.PlacementPolicy.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getReplicasList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.neo.fs.v2.netmap.Replica.serializeBinaryToWriter
    );
  }
  f = this.getContainerBackupFactor();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = this.getSelectorsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.neo.fs.v2.netmap.Selector.serializeBinaryToWriter
    );
  }
  f = this.getFiltersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.neo.fs.v2.netmap.Filter.serializeBinaryToWriter
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.neo.fs.v2.netmap.PlacementPolicy} The clone.
 */
proto.neo.fs.v2.netmap.PlacementPolicy.prototype.cloneMessage = function() {
  return /** @type {!proto.neo.fs.v2.netmap.PlacementPolicy} */ (jspb.Message.cloneMessage(this));
};


/**
 * repeated Replica replicas = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.neo.fs.v2.netmap.Replica>}
 */
proto.neo.fs.v2.netmap.PlacementPolicy.prototype.getReplicasList = function() {
  return /** @type{!Array.<!proto.neo.fs.v2.netmap.Replica>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.neo.fs.v2.netmap.Replica, 1));
};


/** @param {Array.<!proto.neo.fs.v2.netmap.Replica>} value  */
proto.neo.fs.v2.netmap.PlacementPolicy.prototype.setReplicasList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


proto.neo.fs.v2.netmap.PlacementPolicy.prototype.clearReplicasList = function() {
  this.setReplicasList([]);
};


/**
 * optional uint32 container_backup_factor = 2;
 * @return {number}
 */
proto.neo.fs.v2.netmap.PlacementPolicy.prototype.getContainerBackupFactor = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 2, 0));
};


/** @param {number} value  */
proto.neo.fs.v2.netmap.PlacementPolicy.prototype.setContainerBackupFactor = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * repeated Selector selectors = 3;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.neo.fs.v2.netmap.Selector>}
 */
proto.neo.fs.v2.netmap.PlacementPolicy.prototype.getSelectorsList = function() {
  return /** @type{!Array.<!proto.neo.fs.v2.netmap.Selector>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.neo.fs.v2.netmap.Selector, 3));
};


/** @param {Array.<!proto.neo.fs.v2.netmap.Selector>} value  */
proto.neo.fs.v2.netmap.PlacementPolicy.prototype.setSelectorsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


proto.neo.fs.v2.netmap.PlacementPolicy.prototype.clearSelectorsList = function() {
  this.setSelectorsList([]);
};


/**
 * repeated Filter filters = 4;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.neo.fs.v2.netmap.Filter>}
 */
proto.neo.fs.v2.netmap.PlacementPolicy.prototype.getFiltersList = function() {
  return /** @type{!Array.<!proto.neo.fs.v2.netmap.Filter>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.neo.fs.v2.netmap.Filter, 4));
};


/** @param {Array.<!proto.neo.fs.v2.netmap.Filter>} value  */
proto.neo.fs.v2.netmap.PlacementPolicy.prototype.setFiltersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


proto.neo.fs.v2.netmap.PlacementPolicy.prototype.clearFiltersList = function() {
  this.setFiltersList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.neo.fs.v2.netmap.NodeInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.neo.fs.v2.netmap.NodeInfo.repeatedFields_, null);
};
goog.inherits(proto.neo.fs.v2.netmap.NodeInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.neo.fs.v2.netmap.NodeInfo.displayName = 'proto.neo.fs.v2.netmap.NodeInfo';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.neo.fs.v2.netmap.NodeInfo.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.neo.fs.v2.netmap.NodeInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.neo.fs.v2.netmap.NodeInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.neo.fs.v2.netmap.NodeInfo} msg The msg instance to transform.
 * @return {!Object}
 */
proto.neo.fs.v2.netmap.NodeInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    publicKey: msg.getPublicKey_asB64(),
    address: msg.getAddress(),
    attributesList: jspb.Message.toObjectList(msg.getAttributesList(),
    proto.neo.fs.v2.netmap.NodeInfo.Attribute.toObject, includeInstance),
    state: msg.getState()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.neo.fs.v2.netmap.NodeInfo}
 */
proto.neo.fs.v2.netmap.NodeInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.neo.fs.v2.netmap.NodeInfo;
  return proto.neo.fs.v2.netmap.NodeInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.neo.fs.v2.netmap.NodeInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.neo.fs.v2.netmap.NodeInfo}
 */
proto.neo.fs.v2.netmap.NodeInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setPublicKey(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddress(value);
      break;
    case 3:
      var value = new proto.neo.fs.v2.netmap.NodeInfo.Attribute;
      reader.readMessage(value,proto.neo.fs.v2.netmap.NodeInfo.Attribute.deserializeBinaryFromReader);
      msg.getAttributesList().push(value);
      msg.setAttributesList(msg.getAttributesList());
      break;
    case 4:
      var value = /** @type {!proto.neo.fs.v2.netmap.NodeInfo.State} */ (reader.readEnum());
      msg.setState(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.neo.fs.v2.netmap.NodeInfo} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.neo.fs.v2.netmap.NodeInfo.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.neo.fs.v2.netmap.NodeInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.neo.fs.v2.netmap.NodeInfo.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getPublicKey_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = this.getAddress();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getAttributesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.neo.fs.v2.netmap.NodeInfo.Attribute.serializeBinaryToWriter
    );
  }
  f = this.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.neo.fs.v2.netmap.NodeInfo} The clone.
 */
proto.neo.fs.v2.netmap.NodeInfo.prototype.cloneMessage = function() {
  return /** @type {!proto.neo.fs.v2.netmap.NodeInfo} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional bytes public_key = 1;
 * @return {!(string|Uint8Array)}
 */
proto.neo.fs.v2.netmap.NodeInfo.prototype.getPublicKey = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/**
 * optional bytes public_key = 1;
 * This is a type-conversion wrapper around `getPublicKey()`
 * @return {string}
 */
proto.neo.fs.v2.netmap.NodeInfo.prototype.getPublicKey_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getPublicKey()));
};


/**
 * optional bytes public_key = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getPublicKey()`
 * @return {!Uint8Array}
 */
proto.neo.fs.v2.netmap.NodeInfo.prototype.getPublicKey_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getPublicKey()));
};


/** @param {!(string|Uint8Array)} value  */
proto.neo.fs.v2.netmap.NodeInfo.prototype.setPublicKey = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string address = 2;
 * @return {string}
 */
proto.neo.fs.v2.netmap.NodeInfo.prototype.getAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.neo.fs.v2.netmap.NodeInfo.prototype.setAddress = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * repeated Attribute attributes = 3;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.neo.fs.v2.netmap.NodeInfo.Attribute>}
 */
proto.neo.fs.v2.netmap.NodeInfo.prototype.getAttributesList = function() {
  return /** @type{!Array.<!proto.neo.fs.v2.netmap.NodeInfo.Attribute>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.neo.fs.v2.netmap.NodeInfo.Attribute, 3));
};


/** @param {Array.<!proto.neo.fs.v2.netmap.NodeInfo.Attribute>} value  */
proto.neo.fs.v2.netmap.NodeInfo.prototype.setAttributesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


proto.neo.fs.v2.netmap.NodeInfo.prototype.clearAttributesList = function() {
  this.setAttributesList([]);
};


/**
 * optional State state = 4;
 * @return {!proto.neo.fs.v2.netmap.NodeInfo.State}
 */
proto.neo.fs.v2.netmap.NodeInfo.prototype.getState = function() {
  return /** @type {!proto.neo.fs.v2.netmap.NodeInfo.State} */ (jspb.Message.getFieldProto3(this, 4, 0));
};


/** @param {!proto.neo.fs.v2.netmap.NodeInfo.State} value  */
proto.neo.fs.v2.netmap.NodeInfo.prototype.setState = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * @enum {number}
 */
proto.neo.fs.v2.netmap.NodeInfo.State = {
  UNSPECIFIED: 0,
  ONLINE: 1,
  OFFLINE: 2
};


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.neo.fs.v2.netmap.NodeInfo.Attribute = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.neo.fs.v2.netmap.NodeInfo.Attribute.repeatedFields_, null);
};
goog.inherits(proto.neo.fs.v2.netmap.NodeInfo.Attribute, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.neo.fs.v2.netmap.NodeInfo.Attribute.displayName = 'proto.neo.fs.v2.netmap.NodeInfo.Attribute';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.neo.fs.v2.netmap.NodeInfo.Attribute.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.neo.fs.v2.netmap.NodeInfo.Attribute.prototype.toObject = function(opt_includeInstance) {
  return proto.neo.fs.v2.netmap.NodeInfo.Attribute.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.neo.fs.v2.netmap.NodeInfo.Attribute} msg The msg instance to transform.
 * @return {!Object}
 */
proto.neo.fs.v2.netmap.NodeInfo.Attribute.toObject = function(includeInstance, msg) {
  var f, obj = {
    key: msg.getKey(),
    value: msg.getValue(),
    parentsList: jspb.Message.getField(msg, 3)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.neo.fs.v2.netmap.NodeInfo.Attribute}
 */
proto.neo.fs.v2.netmap.NodeInfo.Attribute.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.neo.fs.v2.netmap.NodeInfo.Attribute;
  return proto.neo.fs.v2.netmap.NodeInfo.Attribute.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.neo.fs.v2.netmap.NodeInfo.Attribute} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.neo.fs.v2.netmap.NodeInfo.Attribute}
 */
proto.neo.fs.v2.netmap.NodeInfo.Attribute.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setValue(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.getParentsList().push(value);
      msg.setParentsList(msg.getParentsList());
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.neo.fs.v2.netmap.NodeInfo.Attribute} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.neo.fs.v2.netmap.NodeInfo.Attribute.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.neo.fs.v2.netmap.NodeInfo.Attribute.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.neo.fs.v2.netmap.NodeInfo.Attribute.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getKey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getValue();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getParentsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.neo.fs.v2.netmap.NodeInfo.Attribute} The clone.
 */
proto.neo.fs.v2.netmap.NodeInfo.Attribute.prototype.cloneMessage = function() {
  return /** @type {!proto.neo.fs.v2.netmap.NodeInfo.Attribute} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string key = 1;
 * @return {string}
 */
proto.neo.fs.v2.netmap.NodeInfo.Attribute.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.neo.fs.v2.netmap.NodeInfo.Attribute.prototype.setKey = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string value = 2;
 * @return {string}
 */
proto.neo.fs.v2.netmap.NodeInfo.Attribute.prototype.getValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.neo.fs.v2.netmap.NodeInfo.Attribute.prototype.setValue = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * repeated string parents = 3;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<string>}
 */
proto.neo.fs.v2.netmap.NodeInfo.Attribute.prototype.getParentsList = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.getField(this, 3));
};


/** @param {Array.<string>} value  */
proto.neo.fs.v2.netmap.NodeInfo.Attribute.prototype.setParentsList = function(value) {
  jspb.Message.setField(this, 3, value || []);
};


proto.neo.fs.v2.netmap.NodeInfo.Attribute.prototype.clearParentsList = function() {
  jspb.Message.setField(this, 3, []);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.neo.fs.v2.netmap.NetworkInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.neo.fs.v2.netmap.NetworkInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.neo.fs.v2.netmap.NetworkInfo.displayName = 'proto.neo.fs.v2.netmap.NetworkInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.neo.fs.v2.netmap.NetworkInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.neo.fs.v2.netmap.NetworkInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.neo.fs.v2.netmap.NetworkInfo} msg The msg instance to transform.
 * @return {!Object}
 */
proto.neo.fs.v2.netmap.NetworkInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    currentEpoch: msg.getCurrentEpoch(),
    magicNumber: msg.getMagicNumber()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.neo.fs.v2.netmap.NetworkInfo}
 */
proto.neo.fs.v2.netmap.NetworkInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.neo.fs.v2.netmap.NetworkInfo;
  return proto.neo.fs.v2.netmap.NetworkInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.neo.fs.v2.netmap.NetworkInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.neo.fs.v2.netmap.NetworkInfo}
 */
proto.neo.fs.v2.netmap.NetworkInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setCurrentEpoch(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setMagicNumber(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.neo.fs.v2.netmap.NetworkInfo} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.neo.fs.v2.netmap.NetworkInfo.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.neo.fs.v2.netmap.NetworkInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.neo.fs.v2.netmap.NetworkInfo.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getCurrentEpoch();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = this.getMagicNumber();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.neo.fs.v2.netmap.NetworkInfo} The clone.
 */
proto.neo.fs.v2.netmap.NetworkInfo.prototype.cloneMessage = function() {
  return /** @type {!proto.neo.fs.v2.netmap.NetworkInfo} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional uint64 current_epoch = 1;
 * @return {number}
 */
proto.neo.fs.v2.netmap.NetworkInfo.prototype.getCurrentEpoch = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {number} value  */
proto.neo.fs.v2.netmap.NetworkInfo.prototype.setCurrentEpoch = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional uint64 magic_number = 2;
 * @return {number}
 */
proto.neo.fs.v2.netmap.NetworkInfo.prototype.getMagicNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 2, 0));
};


/** @param {number} value  */
proto.neo.fs.v2.netmap.NetworkInfo.prototype.setMagicNumber = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * @enum {number}
 */
proto.neo.fs.v2.netmap.Operation = {
  OPERATION_UNSPECIFIED: 0,
  EQ: 1,
  NE: 2,
  GT: 3,
  GE: 4,
  LT: 5,
  LE: 6,
  OR: 7,
  AND: 8
};

/**
 * @enum {number}
 */
proto.neo.fs.v2.netmap.Clause = {
  CLAUSE_UNSPECIFIED: 0,
  SAME: 1,
  DISTINCT: 2
};

goog.object.extend(exports, proto.neo.fs.v2.netmap);
